/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mmdd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IdappdsmlStandaloneSetup extends IdappdsmlStandaloneSetupGenerated {

	public static void doSetup() {
		new IdappdsmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
