/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mmdd.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.mmdd.parser.antlr.internal.InternalIdappdsmlParser;
import uk.ac.kcl.inf.mmdd.services.IdappdsmlGrammarAccess;

public class IdappdsmlParser extends AbstractAntlrParser {

	@Inject
	private IdappdsmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIdappdsmlParser createParser(XtextTokenStream stream) {
		return new InternalIdappdsmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Contract";
	}

	public IdappdsmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IdappdsmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
