/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mmdd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IdappdsmlUiModule extends AbstractIdappdsmlUiModule {

	public IdappdsmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
