/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.mmdd.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.mmdd.idappdsml.grammar.ui.internal.GrammarActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IdappdsmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GrammarActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GrammarActivator activator = GrammarActivator.getInstance();
		return activator != null ? activator.getInjector(GrammarActivator.UK_AC_KCL_INF_MMDD_IDAPPDSML) : null;
	}

}
