/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getCustomer <em>Customer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getCompany <em>Company</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getInsurableObjects <em>Insurable Objects</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getPremium <em>Premium</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getIncrease <em>Increase</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getClaim <em>Claim</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Contract#getPeriod <em>Period</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract()
 * @model
 * @generated
 */
public interface Contract extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Customer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customer</em>' containment reference.
   * @see #setCustomer(Customer)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Customer()
   * @model containment="true"
   * @generated
   */
  Customer getCustomer();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getCustomer <em>Customer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Customer</em>' containment reference.
   * @see #getCustomer()
   * @generated
   */
  void setCustomer(Customer value);

  /**
   * Returns the value of the '<em><b>Company</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company</em>' containment reference.
   * @see #setCompany(Company)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Company()
   * @model containment="true"
   * @generated
   */
  Company getCompany();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getCompany <em>Company</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company</em>' containment reference.
   * @see #getCompany()
   * @generated
   */
  void setCompany(Company value);

  /**
   * Returns the value of the '<em><b>Insurable Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insurable Objects</em>' containment reference.
   * @see #setInsurableObjects(InsurableObjects)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_InsurableObjects()
   * @model containment="true"
   * @generated
   */
  InsurableObjects getInsurableObjects();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getInsurableObjects <em>Insurable Objects</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Insurable Objects</em>' containment reference.
   * @see #getInsurableObjects()
   * @generated
   */
  void setInsurableObjects(InsurableObjects value);

  /**
   * Returns the value of the '<em><b>Premium</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Premium</em>' attribute.
   * @see #setPremium(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Premium()
   * @model
   * @generated
   */
  float getPremium();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getPremium <em>Premium</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Premium</em>' attribute.
   * @see #getPremium()
   * @generated
   */
  void setPremium(float value);

  /**
   * Returns the value of the '<em><b>Increase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Increase</em>' attribute.
   * @see #setIncrease(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Increase()
   * @model
   * @generated
   */
  float getIncrease();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getIncrease <em>Increase</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Increase</em>' attribute.
   * @see #getIncrease()
   * @generated
   */
  void setIncrease(float value);

  /**
   * Returns the value of the '<em><b>Claim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Claim</em>' attribute.
   * @see #setClaim(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Claim()
   * @model
   * @generated
   */
  float getClaim();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getClaim <em>Claim</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Claim</em>' attribute.
   * @see #getClaim()
   * @generated
   */
  void setClaim(float value);

  /**
   * Returns the value of the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Period</em>' attribute.
   * @see #setPeriod(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContract_Period()
   * @model
   * @generated
   */
  int getPeriod();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Contract#getPeriod <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Period</em>' attribute.
   * @see #getPeriod()
   * @generated
   */
  void setPeriod(int value);

} // Contract
