/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ContractImpl <em>Contract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ContractImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContract()
   * @generated
   */
  int CONTRACT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__NAME = 0;

  /**
   * The feature id for the '<em><b>Customer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__CUSTOMER = 1;

  /**
   * The feature id for the '<em><b>Company</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__COMPANY = 2;

  /**
   * The feature id for the '<em><b>Insurable Objects</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__INSURABLE_OBJECTS = 3;

  /**
   * The feature id for the '<em><b>Premium</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__PREMIUM = 4;

  /**
   * The feature id for the '<em><b>Increase</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__INCREASE = 5;

  /**
   * The feature id for the '<em><b>Claim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__CLAIM = 6;

  /**
   * The feature id for the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT__PERIOD = 7;

  /**
   * The number of structural features of the '<em>Contract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTRACT_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CustomerImpl <em>Customer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CustomerImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCustomer()
   * @generated
   */
  int CUSTOMER = 1;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER__ADDRESS = 0;

  /**
   * The number of structural features of the '<em>Customer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CompanyImpl <em>Company</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CompanyImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompany()
   * @generated
   */
  int COMPANY = 2;

  /**
   * The feature id for the '<em><b>Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY__ADDRESS = 0;

  /**
   * The number of structural features of the '<em>Company</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPANY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InsurableObjectsImpl <em>Insurable Objects</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InsurableObjectsImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInsurableObjects()
   * @generated
   */
  int INSURABLE_OBJECTS = 3;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECTS__OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Insurable Objects</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InsurableObjectImpl <em>Insurable Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InsurableObjectImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInsurableObject()
   * @generated
   */
  int INSURABLE_OBJECT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECT__NAME = 0;

  /**
   * The number of structural features of the '<em>Insurable Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSURABLE_OBJECT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Contract <em>Contract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contract</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract
   * @generated
   */
  EClass getContract();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Contract#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getName()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Contract#getCustomer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Customer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getCustomer()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Customer();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Contract#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Company</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getCompany()
   * @see #getContract()
   * @generated
   */
  EReference getContract_Company();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Contract#getInsurableObjects <em>Insurable Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Insurable Objects</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getInsurableObjects()
   * @see #getContract()
   * @generated
   */
  EReference getContract_InsurableObjects();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Contract#getPremium <em>Premium</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Premium</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getPremium()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Premium();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Contract#getIncrease <em>Increase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Increase</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getIncrease()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Increase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Contract#getClaim <em>Claim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Claim</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getClaim()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Claim();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Contract#getPeriod <em>Period</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Period</em>'.
   * @see org.xtext.example.mydsl.myDsl.Contract#getPeriod()
   * @see #getContract()
   * @generated
   */
  EAttribute getContract_Period();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Customer <em>Customer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customer</em>'.
   * @see org.xtext.example.mydsl.myDsl.Customer
   * @generated
   */
  EClass getCustomer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Customer#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.mydsl.myDsl.Customer#getAddress()
   * @see #getCustomer()
   * @generated
   */
  EAttribute getCustomer_Address();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Company <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Company</em>'.
   * @see org.xtext.example.mydsl.myDsl.Company
   * @generated
   */
  EClass getCompany();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Company#getAddress <em>Address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Address</em>'.
   * @see org.xtext.example.mydsl.myDsl.Company#getAddress()
   * @see #getCompany()
   * @generated
   */
  EAttribute getCompany_Address();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.InsurableObjects <em>Insurable Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insurable Objects</em>'.
   * @see org.xtext.example.mydsl.myDsl.InsurableObjects
   * @generated
   */
  EClass getInsurableObjects();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.InsurableObjects#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see org.xtext.example.mydsl.myDsl.InsurableObjects#getObjects()
   * @see #getInsurableObjects()
   * @generated
   */
  EReference getInsurableObjects_Objects();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.InsurableObject <em>Insurable Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Insurable Object</em>'.
   * @see org.xtext.example.mydsl.myDsl.InsurableObject
   * @generated
   */
  EClass getInsurableObject();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.InsurableObject#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.InsurableObject#getName()
   * @see #getInsurableObject()
   * @generated
   */
  EAttribute getInsurableObject_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ContractImpl <em>Contract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ContractImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getContract()
     * @generated
     */
    EClass CONTRACT = eINSTANCE.getContract();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__NAME = eINSTANCE.getContract_Name();

    /**
     * The meta object literal for the '<em><b>Customer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__CUSTOMER = eINSTANCE.getContract_Customer();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__COMPANY = eINSTANCE.getContract_Company();

    /**
     * The meta object literal for the '<em><b>Insurable Objects</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTRACT__INSURABLE_OBJECTS = eINSTANCE.getContract_InsurableObjects();

    /**
     * The meta object literal for the '<em><b>Premium</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__PREMIUM = eINSTANCE.getContract_Premium();

    /**
     * The meta object literal for the '<em><b>Increase</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__INCREASE = eINSTANCE.getContract_Increase();

    /**
     * The meta object literal for the '<em><b>Claim</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__CLAIM = eINSTANCE.getContract_Claim();

    /**
     * The meta object literal for the '<em><b>Period</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTRACT__PERIOD = eINSTANCE.getContract_Period();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CustomerImpl <em>Customer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CustomerImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCustomer()
     * @generated
     */
    EClass CUSTOMER = eINSTANCE.getCustomer();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMER__ADDRESS = eINSTANCE.getCustomer_Address();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CompanyImpl <em>Company</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CompanyImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCompany()
     * @generated
     */
    EClass COMPANY = eINSTANCE.getCompany();

    /**
     * The meta object literal for the '<em><b>Address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPANY__ADDRESS = eINSTANCE.getCompany_Address();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InsurableObjectsImpl <em>Insurable Objects</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InsurableObjectsImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInsurableObjects()
     * @generated
     */
    EClass INSURABLE_OBJECTS = eINSTANCE.getInsurableObjects();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSURABLE_OBJECTS__OBJECTS = eINSTANCE.getInsurableObjects_Objects();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InsurableObjectImpl <em>Insurable Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InsurableObjectImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInsurableObject()
     * @generated
     */
    EClass INSURABLE_OBJECT = eINSTANCE.getInsurableObject();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSURABLE_OBJECT__NAME = eINSTANCE.getInsurableObject_Name();

  }

} //MyDslPackage
