/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.mmdd.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.mmdd.idappdsml.grammar.ui.internal.GrammarActivator;

public class IdappdsmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GrammarActivator.getInstance().getInjector("uk.ac.kcl.inf.mmdd.Idappdsml");
	}

}
